# Bike rental data columns
INSTANT_COL = 0
SEASON_COL = 1
YEAR_COL = 2
MONTH_COL = 3
HOUR_COL = 4
HOLIDAY_COL = 5
WEEKDAY_COL = 6
WORKINGDAY_COL = 7

WEATHERSIT_COL = 8
TEMP_COL = 9
ATEMP_COL = 10
HUMIDITY_COL = 11
WINDSPEED_COL = 12

CASUAL_USERS_COL = 13
REGISTERED_USERS_COL = 14
TOTAL_COUNT_COL = 15


# de-normalization values
MAX_TEMP = 41
MAX_ATEMP = 50
MAX_HUMIDITY = 100
MAX_WINDSPEED = 67

